name: tenants

services:
  postgres:
    image: postgres
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: auxano
      POSTGRES_USER: mariam
      POSTGRES_PASSWORD: Maryam@20
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: