# Generated by Django 5.2.4 on 2025-08-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestforquote',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
